### ISSUE TITLE
License and possible contributions?

### ISSUE THREAD

**Issue by yoelcortes** [UBCEnvision/CHBE241#38]
Hi!

I'm happy how this repository integrates open-source tools in Python (like Caleb's thermo library) for educational purposes. I was wondering what is the license for this repository? The reason I ask is because I'd like to contribute a few examples using BioSTEAM (https://biosteam.readthedocs.io/en/latest/), and I'd like to know how welcoming is this repository to outside contributions. My hope is that my examples can promote the adoption of BioSTEAM to students early in their career. 

Thanks,
Have a nice day!

**Comment by yoelcortes** [comment]
Hi Jonathan,

It's probably been a while since you've worked on this repository and you must be busy working on other matters. I'll be assuming this repository is an Open Educational Resource, as described in some of your awesome published work (https://ojs.library.queensu.ca/index.php/PCEEA/article/view/14183). 

I'll fork this repository and try to contribute back as much as possible, but I might create a BioSTEAM-centered version (which would be open-source) later on in my career.

Thanks for your work on this,
Have a nice day!

**Comment by jverrett** [comment]
Hi Yoel,

It should be published under CC-BY. I'll add a license file in there to make that clear. Feel free to use it :)

Best,

Jonathan
