### ISSUE TITLE
Introductions

### ISSUE THREAD

**Issue by jverrett** [UBCEnvision/CHBE241#5]
For the introductions I would change them to include a learning objective for students  written in the form of what they should be able to do by the end of the section. An example could be for Block Diagrams, currently there is:

"Block flow diagrams (BFD) are the first step in designing a chemical process. A BFD is the simplest form of flow diagrams used in industry. The blocks in a BFD can represent anything from a single piece of equipment to an entire plant."

In this case I like the intro text, but would like to have the following even before:

"By the end of this section [if that part of a notebook is called that] you should be able to: draw a block flow diagram based on a process description."

Usually these objectives come in the form:

"By the end of this section you should be able to: (verb) (content...)"

This is a very common structure. You'll find the same at the start of my slides that I'll upload to slack. I'm not sure if it would be best to have both objectives and intro sections? Something to discuss.

**Comment by jverrett** [comment]
Also don't feel like you need to go back and change this now. One option is to do this moving forward and then come back to edit previous pages.

**Comment by saidzaid** [comment]
Sounds good, I think moving forward for now is the best option!

**Comment by jverrett** [comment]
Perfect. You can find the learning objectives I wrote for all the classes last year in the word doc I uploaded earlier with the content topics as well if you want some inspiration and examples.
