### ISSUE TITLE
Diagrams - I/O, BFD, PFD

### ISSUE THREAD

**Issue by jverrett** [UBCEnvision/CHBE241#6]
These should all be separate sections as they are specific in terms of what each diagram contains. See the slides on ch 6.9 for examples.

**Comment by saidzaid** [comment]
Sorry, I was under the impression that I/O and PFD were under the umbrella of BFD. Each one of these on their own is short so do you think it is ok to keep them under the same section and title the section differently? In light of this, under Overview, should I make a new subsection under the overview for BFD specifically?

**Comment by jverrett** [comment]
They can be in the same section, but should be separated and defined specifically. You can title the section "Input-Output (I/O) and Block Flow Diagrams (BFD)". In the overview you can talk about both, and then define them in subsections from there.

**Comment by saidzaid** [comment]
Ok sounds good!

**Comment by saidzaid** [comment]
I have vhanged the sections as to not have I-O under the umbrella of BFD.
