### ISSUE TITLE
Flow rates page

### ISSUE THREAD

**Issue by jverrett** [UBCEnvision/CHBE241#9]
Include that the dot above a symbol represents per unit time

molar flows - when mentioning "elements" are conserved, change this to "atomic species (eg. N, O, C)"

Volumetric flow rate - may change with density changes, which are generally small for liquid/solids but can be appreciable for gases if pressure changes occur. You have density relationship later, specifying this earlier would be more intuitive for me.

I would move rotameter description up under the rotameter and number rotameter and orifice 1 and 2

Manometer - earliest tool rather than most common, other methods are more common now.

**Comment by saidzaid** [comment]
1. For the dot above, I dont see any of the varibles that dont have it.
2. Changed.
3. Changed.
4.  Moved around the pictures and discriptions. Numbered.
5. Changed.
